# https://webdriver.io/docs/githubactions
name: Web - Scheduled
on:
  schedule:
    - cron: '20,50 * * * 1-5' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup NPM
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install NPM
          run: npm install

        - name: Test
          run: npm run wdio:githubaction env=qa browser=chrome
          # continue-on-error: true

        - name: Upload Report
          # if: github.event.inputs.artifact == 'true'
          uses: actions/upload-artifact@v3
          with:
            name: allure
            path: ./reports/allure/allure-report
